# Generated by Django 6.0.5 on 2026-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_middle_name_user_name_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
    ]
