# Generated by Django 6.0.1 on 2026-02-03 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='college',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.college'),
            preserve_default=False,
        ),
    ]
